### PR TITLE
Support svg images

### LINKED ISSUE #12: Svg support
.NET MAUI application uses svg images for icons. Let's add badges for them

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
Fixes #12

### CODE REVIEW

**Comment by VladislavAntonyuk** [comment]
@damienaicheh could you please review the PR?

**Comment by damienaicheh** [comment]
Hello @VladislavAntonyuk  thanks for the ping, I will try to look at it yes

**Comment by VladislavAntonyuk** [comment]
Sorry for disturbing you @damienaicheh  Any chance you review this PR?
I don't want to publish the plugin to Azure marketplace, however I really need this implementation.

**Comment by damienaicheh** [comment]
Hello, I am not available right now to look at it sorry. Maybe next month

**Comment by VladislavAntonyuk** [comment]
Hello @damienaicheh! Sorry for disturbing you again. Do you have some time to review this PR? Thank you

**Comment by VladislavAntonyuk** [comment]
Hello @damienaicheh! Sorry for disturbing you again. Do you have some time to review this PR? Thank you.

**Pull request closed without merging**
